sudo: required
language: android
android:
  components:
    - tools
    # The BuildTools version used by your project
    - build-tools-23.0.3
    # The SDK version used to compile your project
    - android-23
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  # Show OS
  - cat /etc/os-release
  # PPAs
  - sudo add-apt-repository -y ppa:chris-lea/libsodium
  - sudo apt-get update
  # Libsodium
  - sudo apt-get install -y libsodium-dev
script:
  - ./gradlew build test
