version: 2

references:
  test-steps: &test-steps

    # Checkout code
    - checkout

    # Start SaltyRTC server
    - run: saltyrtc-server-launcher > /saltyrtc/server.pid && sleep 2

    # Handle dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
    - run: ./gradlew dependencies
    - save_cache:
        paths:
          - ~/.m2
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    # Create JKS keystore
    - run: keytool -import -trustcacerts -alias root -file /saltyrtc/certs/saltyrtc.crt -keystore saltyrtc.jks -storetype JKS -storepass saltyrtc -noprompt

    # Run tests
    - run: ./gradlew test

    # Stop SaltyRTC server
    - run: kill -INT $(cat /saltyrtc/server.pid)

jobs:
  test-openjdk8:
    docker:
      - image: saltyrtc/circleci-image-java:openjdk8
    steps: *test-steps
  test-android-compat:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run: bash .circleci/check_android_support.sh

workflows:
  version: 2
  build:
    jobs:
      - test-openjdk8:
          filters:
            branches:
              ignore:
                - gh-pages
      - test-android-compat:
          filters:
            branches:
              ignore:
                - gh-pages
